# Site settings
url: http://www.rogertinsley.co.uk
title: Roger Tinsley
subtitle: Full stack developer.
author: Roger Tinsley
simple_search: http://google.com/search
description: roger tinsley, programmer, architecture, microsoft, .net, dotnet, azure

# Google analytics
google_analytics:

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: rogertinsley

# Social icons
show_social_icons: false
github_username: rogertinsley
stackoverflow_id:
twitter_username: rogertinsley
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     20
sass:
  compressed: true
gems:
  - jekyll-sitemap
